
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.rmi.Naming;
import java.sql.Connection;
import java.sql.*;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */

/**
 *
 * @author Preeti
 */
public class ScheduleClass extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleClass
     */
    MyListener m = new MyListener();

    public ScheduleClass() {
        initComponents();
        this.getFacultyId();
    }

    public class MyListener implements ItemListener {

        @Override
        public void itemStateChanged(ItemEvent e) {
            try {
                String s = jComboBox7.getSelectedItem().toString();
                Admin_Interface mid = (Admin_Interface) Naming.lookup("rmi://localhost/virtual");
                String name = mid.getFacultyname(s);
                jTextField2.setText(name);
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }
    }

    public void getFacultyId() {
        jComboBox7.removeItemListener(m);
        try {
            jComboBox7.removeAllItems();
            Admin_Interface mid = (Admin_Interface) Naming.lookup("rmi://localhost/virtual");
            Vector v = mid.getFacultyId();
            for (int i = 0; i < v.size(); i++) {
                jComboBox7.addItem(v.elementAt(i));
            }
        } catch (Exception e) {
        }
        jComboBox7.addItemListener(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(980, 520));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin001.png"))); // NOI18N
        jLabel1.setText("  Schedule Class");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filesave.png"))); // NOI18N
        jButton1.setText("  Submit");
        jButton1.setHideActionText(true);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Course :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Branch :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Year :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Semester :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Subject :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Faculty Id :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Faculty Name :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Time :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Duration :");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "B. TECH.", "M.TECH.", "M.C. A.", "M. B. A." }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "CS", "IT", "EC", "EN", "ME", "CIVIL", "FINANCE", "MARKETING", "ENTREPRENEURSHIP", "ACCOUNTING", "MANAGMENT", "REAL ESTATE", "NONPROFIT", "HEALTH CARE", "HUMAN SREVICES MANAGMENT", "SPORTS MANAGMENT", "ECONOMICS", "ORGANIZATIONAL MANAGEMENT", "STRUCTURAL ENGINEERING", "POWER SYSTEM", "ELECTRICAL DRIVES", "DIGITAL COMMUNICATION", "MICROWAVE MILLIMETER", "VLSI", "INDUSTRIAL DESIGN", "THERMAL ENGINEERING", "MAINTENANCE ENGINEERING", "NANO TECHNOLOGY", "REMOTE SENSING", "BOI INFORMATICS", "ENERGY", "TRANSPOTATION ENGINEERING", "COMPUTER SCIENCE & ENGINEERING", "INFORMATION SECURITY", "ENGINEERING MATERIALS", "STRESS & VIBRATION ANALYSIS", "HYDRO", "ENVIRONMENT", "GEOTECHNICAL" }));

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "1", "2", "3", "4" }));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jComboBox7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jComboBox8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "09:00", "09:45", "10:30", "11:15", "12:00", "12:45", "01:30", "02:15", "03:00", "03:45", "04:00", "" }));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextField4.setText("00:45:00");

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(153, 153, 153));
        jTextField12.setText("Enter Your Subject");
        jTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField12FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField12FocusLost(evt);
            }
        });
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 313, Short.MAX_VALUE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField4)
                    .addComponent(jTextField12))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTextField7.setBackground(new java.awt.Color(204, 204, 204));
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        jTextField7.setText("Add Other Course");
        jTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField7FocusGained(evt);
            }
        });

        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        jTextField8.setText("Add Other Branch");
        jTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField8FocusGained(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Add");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Add");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jTextField8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusGained
        String s = jTextField7.getText();
        if (s.equals("Add Other Course")) {
            jTextField7.setText("");
        }
    }//GEN-LAST:event_jTextField7FocusGained

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String s = jTextField7.getText();
        if ((!(s.equals(""))) && (!(s.equals("Add Other Course")))) {
            jComboBox1.addItem(s);
        } else {
            JOptionPane.showMessageDialog(this, "Please Input Course Name");
        }
        jTextField7.setText("Add Other Course");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusGained
        String s = jTextField8.getText();
        if (s.equals("Add Other Branch")) {
            jTextField8.setText("");
        }
    }//GEN-LAST:event_jTextField8FocusGained

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String s = jTextField8.getText();
        if ((!(s.equals(""))) && (!(s.equals("Add Other Branch")))) {
            jComboBox2.addItem(s);
        } else {
            JOptionPane.showMessageDialog(this, "Please Input Branch Name");
        }
        jTextField8.setText("Add Other Branch");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jComboBox1.getSelectedIndex() == 0 || jComboBox2.getSelectedIndex() == 0 || jComboBox3.getSelectedIndex() == 0 || jComboBox4.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Fill the values.");
        } else {
            try {
                String s1 = jComboBox1.getSelectedItem().toString();
                String s2 = jComboBox2.getSelectedItem().toString();
                String s3 = jComboBox4.getSelectedItem().toString();
                String s4 = jComboBox3.getSelectedItem().toString();
                String s5 = jTextField12.getText();
                String s6 = jTextField2.getText();
                String s7 = jComboBox8.getSelectedItem().toString();
                String s8 = jTextField4.getText();
                String s9 = jComboBox7.getSelectedItem().toString();
                Admin_Interface mid = (Admin_Interface) Naming.lookup("rmi://localhost/virtual");
                boolean b = mid.submit(s9, s7);
                boolean b1 = mid.submit1(s1, s2, s3, s4, s7);
                if (b) {
                    JOptionPane.showMessageDialog(this, "Faculty are busy in  another class.");
                    jTextField2.setText("");
                    //jTextField4.setText("");
                    jTextField12.setText("");
                    jComboBox8.setSelectedItem("09:00");
                    jComboBox2.removeAllItems();
                    jComboBox3.removeAllItems();
                    jComboBox4.removeAllItems();
                    jComboBox1.setSelectedItem("--SELECT--");
                } else if (b1) {
                    JOptionPane.showMessageDialog(this, "Classes are already scheduled.");
                    jTextField2.setText("");
                    jTextField12.setText("");
                    jComboBox8.setSelectedItem("09:00");
                    jComboBox2.removeAllItems();
                    jComboBox3.removeAllItems();
                    jComboBox4.removeAllItems();
                    jComboBox1.setSelectedItem("--SELECT--");
                } else {
                    Admin_Interface mid1 = (Admin_Interface) Naming.lookup("rmi://localhost/virtual");
                    int num = mid1.user(s9, s6, s1, s2, s3, s4, s5, s7, s8);
                    JOptionPane.showMessageDialog(this, "Values are submitted!");
                    jTextField2.setText("");
                    //jTextField4.setText("");
                    jTextField12.setText("");
                    jComboBox8.setSelectedItem("09:00");
                    jComboBox2.removeAllItems();
                    jComboBox3.removeAllItems();
                    jComboBox4.removeAllItems();
                    jComboBox1.setSelectedItem("--SELECT--");
                    //  jComboBox7.removeItemListener(m);
                    //jComboBox7.addItemListener(m);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        try {
            jComboBox2.removeAllItems();
            jComboBox3.removeAllItems();
            jComboBox4.removeAllItems();
            //String course[]={"B.TECH","M.TECH","MCA","MBA"};
            String branch1[] = {"--SELECT--", "CS", "IT", "EC", "EN", "ME", "CIVIL"};
            String branch2[] = {"--SELECT--", "FINANCE", "MARKETING", "ENTREPRENEURSHIP", "ACCOUNTING", "MANAGMENT", "REAL ESTATE", "NONPROFIT", "HEALTH CARE", "HUMAN SREVICES MANAGMENT", "SPORTS MANAGMENT", "ECONOMICS", "ORGANIZATIONAL MANAGEMENT"};
            String branch3[] = {"--SELECT--", "STRUCTURAL ENGINEERING", "POWER SYSTEM", "ELECTRICAL DRIVES", "DIGITAL COMMUNICATION", "MICROWAVE MILLIMETER", "VLSI", "INDUSTRIAL DESIGN", "THERMAL ENGINEERING", "MAINTENANCE ENGINEERING", "NANO TECHNOLOGY", "REMOTE SENSING", "BOI INFORMATICS", "ENERGY", "TRANSPOTATION ENGINEERING", "COMPUTER SCIENCE & ENGINEERING", "INFORMATION SECURITY", "ENGINEERING MATERIALS", "STRESS & VIBRATION ANALYSIS", "HYDRO", "ENVIRONMENT", "GEOTECHNICAL"};
            String year1[] = {"--SELECT--", "1", "2", "3", "4"};
            String year2[] = {"--SELECT--", "1", "2"};
            String year3[] = {"--SELECT--", "1", "2", "3"};
            String sem1[] = {"--SELECT--", "1", "2", "3", "4", "5", "6", "7", "8"};
            String sem2[] = {"--SELECT--", "1", "2", "3", "4"};
            String sem3[] = {"--SELECT--", "1", "2", "3", "4", "5", "6"};

            if (jComboBox1.getSelectedItem().toString().equals("B. TECH.")) {
                for (int i = 0; i < branch1.length; i++) {
                    jComboBox2.addItem(branch1[i]);
                    jComboBox2.setEnabled(true);
                }
                for (int i = 0; i < year1.length; i++) {
                    jComboBox4.addItem(year1[i]);
                    //jComboBox4.setEnabled(true);

                }
                for (int i = 0; i < sem1.length; i++) {
                    jComboBox3.addItem(sem1[i]);
                    //jComboBox3.setEnabled(true);
                }

            } else if (jComboBox1.getSelectedItem().toString().equals("M.TECH.")) {
                for (int i = 0; i < branch3.length; i++) {
                    jComboBox2.addItem(branch3[i]);
                    jComboBox2.setEnabled(true);
                }

                for (int i = 0; i < year2.length; i++) {
                    jComboBox4.addItem(year2[i]);
                    jComboBox4.setEnabled(true);
                }
                for (int i = 0; i < sem2.length; i++) {
                    jComboBox3.addItem(sem2[i]);
                    //jComboBox3.setEnabled(true);
                }
            } else if (jComboBox1.getSelectedItem().toString().equals("M.C. A.")) {
                jComboBox2.setEnabled(false);
                for (int i = 0; i < year3.length; i++) {
                    jComboBox4.addItem(year3[i]);
                    jComboBox4.setEnabled(true);
                }
                for (int i = 0; i < sem3.length; i++) {
                    jComboBox3.addItem(sem3[i]);
                    //jComboBox3.setEnabled(true);
                }
            } else if (jComboBox1.getSelectedItem().toString().equals("M. B. A.")) {
                for (int i = 0; i < branch2.length; i++) {
                    jComboBox2.addItem(branch2[i]);
                    jComboBox2.setEnabled(true);
                }
                for (int i = 0; i < year2.length; i++) {
                    jComboBox4.addItem(year2[i]);
                    jComboBox4.setEnabled(true);
                }
                for (int i = 0; i < sem2.length; i++) {
                    jComboBox3.addItem(sem2[i]);
                    //jComboBox3.setEnabled(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jTextField12FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField12FocusGained
        String s = jTextField12.getText();
        if (s.equals("Enter Your Subject")) {
            jTextField12.setText("");
        }
    }//GEN-LAST:event_jTextField12FocusGained

    private void jTextField12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField12FocusLost
        String s = jTextField12.getText();
        if (s.equals("")) {
            jTextField12.setText("Enter Your Subject");
        }
    }//GEN-LAST:event_jTextField12FocusLost

    private void jTextField12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyTyped
        jTextField12.setForeground(Color.black);
    }//GEN-LAST:event_jTextField12KeyTyped
    @SuppressWarnings("unchecked")
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ScheduleClass().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
